baseURL = "https://blog.kurtstories.com"
languageCode = "zh-tw"
title = "Kurt Liao"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Kurt"
  description = "Embrace who you are, and go with the flowğŸ”¹"
  github = "kurt-liao"
  enableGithubFollowers = true # Set to true to show your real github followers(params.github is required)
  twitter = "cn91288"
  linkedin = "kurt-liao-07360b17b"
  email = "vermouth0226@gmail.com"
  stackoverflow="10389571"
  lastmod = true
  userStatusEmoji = "ğŸ˜‰"
  favicon = "/images/avatar.png"
  avatar = "/images/avatar.png"
  location = "Taiwan"
  enableGitalk = true
  rss = true
  enableLocalSearch = true # Set to true if you want to have keyword search locally(params.rss true is required)
  sponsorLink = "Your external sponsor link; For me, I use buymeacoffee link" # Set the link if you want to have a sponsor button and let audience know the your donation link
  customStyleFile = "your css file name"
  gtmId = "your gtm id"
    
  [params.gitalk]
    accessToken = "Your Github access token" # Generate token from github settings  
    repo = "kurt-liao.github.io" # ä½ è¦ç”¨ä¾†å­˜æ”¾ issue çš„ repo åå­—(ä¸ä¸€å®šè¦æ˜¯ä½ çš„ github page repo)
    owner = "kurt-liao" # ä½ çš„GitHub ID
    admin = "kurt-liao" # ä½ çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é é¢çš„é€£çµå°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è¨­ç½®ç‚ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å“¡ç™»éŒ„ï¼Œæœƒè‡ªå‹•å‰µå»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å“¡æ‰‹å‹•æ·»åŠ ç¬¬ä¸€å€‹è©•è«–(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Link"
    href = "https://github.com/kurt-liao"
  [[params.links]]
    title = "Link2"
    href = "https://github.com/kurt-liao/github-style-plus"
    icon = "https://blog.kurtstories.com/images/avatar.png"

  [[params.customOrgs]]
    link = "https://github.com/kurt-project"
    img = "kurt-project.png" #Put your assets in static folder
    name = "kurt-project"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
